### ISSUE TITLE
Add support of Java 8

### ISSUE THREAD

**Issue by solo-rh** [etspaceman/kinesis4cats#119]
Environment: scala 2.13 application running on java 8

Exception on receive message from kinesis:

```
Exception in thread "io-compute-3" java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
	at kinesis4cats.syntax.ByteBufferSyntax$ByteBufferOps$.asArray$extension(bytebuffer.scala:42)
	at kinesis4cats.syntax.ByteBufferSyntax$ByteBufferOps$.asBase64String$extension(bytebuffer.scala:64)
	at kinesis4cats.logging.instances.show$.$anonfun$byteBufferShow$1(show.scala:61)
	at cats.Show$Ops.show(Show.scala:52)
	at cats.Show$Ops.show$(Show.scala:52)
	at cats.Show$ToShowOps$$anon$1.show(Show.scala:57)
	at kinesis4cats.ShowBuilder.$anonfun$add$3(ShowBuilder.scala:55)
	at scala.Option.fold(Option.scala:263)
	at kinesis4cats.ShowBuilder.add(ShowBuilder.scala:55)
	at kinesis4cats.kcl.RecordProcessor$LogEncoders$.$anonfun$show$8(RecordProcessor.scala:478)
	at cats.instances.ListInstances.$anonfun$catsStdShowForList$2(list.scala:278)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:584)
	at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1221)
	at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1216)
	at scala.collection.AbstractIterator.addString(Iterator.scala:1300)
	at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1166)
	at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1164)
	at scala.collection.AbstractIterator.mkString(Iterator.scala:1300)
	at cats.instances.ListInstances.$anonfun$catsStdShowForList$1(list.scala:278)
	at kinesis4cats.logging.instances.show$.$anonfun$showLogEncoder$1(show.scala:37)
	at kinesis4cats.logging.LogEncoder$$anon$2.encode(LogEncoder.scala:62)
	at kinesis4cats.logging.LogContext.$anonfun$addEncoded$2(LogContext.scala:54)
	at scala.Option.fold(Option.scala:263)
	at kinesis4cats.logging.LogContext.addEncoded(LogContext.scala:54)
	at kinesis4cats.kcl.RecordProcessor.$anonfun$processRecords$3(RecordProcessor.scala:139)
	at cats.effect.IOFiber.succeeded(IOFiber.scala:1170)
	at cats.effect.IOFiber.runLoop(IOFiber.scala:240)
	at cats.effect.IOFiber.execR(IOFiber.scala:1317)
	at cats.effect.IOFiber.run(IOFiber.scala:112)
	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:485)
java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
	at kinesis4cats.syntax.ByteBufferSyntax$ByteBufferOps$.asArray$extension(bytebuffer.scala:42)
	at kinesis4cats.syntax.ByteBufferSyntax$ByteBufferOps$.asBase64String$extension(bytebuffer.scala:64)
	at kinesis4cats.logging.instances.show$.$anonfun$byteBufferShow$1(show.scala:61)
	at cats.Show$Ops.show(Show.scala:52)
	at cats.Show$Ops.show$(Show.scala:52)
	at cats.Show$ToShowOps$$anon$1.show(Show.scala:57)
	at kinesis4cats.ShowBuilder.$anonfun$add$3(ShowBuilder.scala:55)
	at scala.Option.fold(Option.scala:263)
```

Same code works well on JDK17

**Comment by solo-rh** [comment]
Fix: need to add a scalacOption `"-release:8"`

**Comment by etspaceman** [comment]
Good call-out

**Comment by etspaceman** [comment]
Closed with https://github.com/etspaceman/kinesis4cats/pull/120
